### ISSUE TITLE
New feature: Save Lab

### ISSUE THREAD

**Issue by junkiattan** [PowerPointLabs/PowerPointLabs#1587] opened 2018-02-03 05:57 UTC
Allows users to select a few slides and save them in a separate presentation. All should be copied over, preserving the animations, as well as the notes in each slide if there are any

**Comment by leeyh20** [comment] 2018-03-21 04:16
Duplicate of #610 actually, remember to close the other issue too.

**Closed** 2018-04-21 02:31 UTC
Labels: c.Feature, d.Contributors
