### ISSUE TITLE
Support saving slides

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#610] opened 2014-11-23 09:36 UTC
That is, save/reuse entire slides.
Not sure if we can do this in a scalable way though.

**Comment by kai33** [comment] 2016-01-30 17:46
feasible

**Comment by initialshl** [comment] 2017-01-30 11:55
Can I try doing this?

**Comment by damithc** [comment] 2017-01-30 11:57
@initialshl sure give it a try.

**Comment by YuPeiHenry** [comment] 2019-01-28 07:11
Closing because duplicate of #1587

**Closed by YuPeiHenry** 2019-01-28 07:11 UTC
Labels: d.Contributors, d.Difficult, f-ShapesLab, p.Low
