### ISSUE TITLE
Crop to same dimensions: support models that are shapes

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1222] opened 2017-03-19 06:59 UTC
The current version requires the model (i.e. the first selected object) to be a picture. However, it also makes sense to use a shape as the model. e.g. rectangles

**Comment by initialshl** [comment] 2017-07-20 06:50
Duplicate of #1383 
Closing issue.

**Closed by initialshl** 2017-07-20 06:50 UTC
Labels: c.Enhancement, f-CropLab, p.Low
