### ISSUE TITLE
PowerPoint open in background after closing

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1432] opened 2017-06-08 07:07 UTC
Currently, we have 3 "background" powerpoints:
- Shapes Lab
- Sync Lab
- Picture Slides Lab

When any of the two are open together, they will not close properly when PowerPoint is closed. This is because the codes check if 2 ppt are open in their respective onclose methods.

We should think of a way to ensure that all the powerpoints are closed properly when the user closes the main active powerpoint.

**Comment by leeyh20** [comment] 2018-03-22 05:28
Not able to reproduce in PPT 2016. Which PPT version did you use?

**Comment by blewjy** [comment] 2019-01-26 13:16
Seem like this issue is still not resolved, I'm also encountering problems of background ppts not closing when at least 2 of the 3 labs are opened. Will be addressing this in a PR.

**Closed** 2019-02-20 15:13 UTC
Labels: c.Bug, d.Moderate, p.Medium, s.InProgress
