### ISSUE TITLE
'animate in slide' stops working sometimes

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#771] opened 2015-07-16 07:04 UTC
I've noticed this twice now. Animate-in-slide breaks at times (it adds some animations, but not the move animations), after restarting Powerpoint, it works again.

**Comment by kai33** [comment] 2015-10-20 10:18
Currently 2 users reported they encountered similar issue on Auto Animate, and 
1. cannot be resolved by restarting ppt
2. cannot be resolved by re-installing VSTO runtime

.Both users are using Win10 and Office365 (Office 2013).

The generated animations don't move at all (looks like the algorithm treats the current slide as the next slide when the issue happens, so no movement is generated).

One user claims he can re-produce the error, but I cannot re-produce it in Yan Xu's device (also Win10 and Office13)

**Comment by damithc** [comment] 2015-10-20 14:02
Yan Xu's set is exactly same as the other two users?

**Comment by kai33** [comment] 2015-10-20 14:28
Found the cause at
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/DefaultMotionAnimation.cs#L225

self note:
when construct the motion path (a string), we need to provide the coordinates (float numbers) as the positions to move to.

so float number (coordinate) here is converted to string (the motion path).

cause:
In certain PCs, they have settings that when convert float into string, the dot '.' will be replaced by comma ',', which will make the motion path not parsable (looks like it doesn't move).

**Comment by damithc** [comment] 2015-10-20 14:47
Nice :-)

-- 
Sent from a mobile device.

**Closed** 2015-10-30 16:30 UTC
Labels: Feature.AnimationsLab, Priority.Medium, status.releaseCandidate, type-bug
