### ISSUE TITLE
Suddenly failing tests, mostly from PSL

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1602] opened 2018-02-08 11:48 UTC
TestApplyStyle (PSL)
TestPreviewStyle (PSL)
TestTextEffect (PSL)
TestInsertImageReference(PSL) 
-> ComException: Interface not registered

TestSyncGradientFill (SyncLab) (manual testing shows that this still works fine)
-> Similarity 0.7xxx

The above tests suddenly failed on me for all branches, for PPT2013, 2016. In other words, no code nor files were changed. Seems to be a Powerpoint issue, could have appeared after attempting too many powerpoint install/uninstalls with different installers. 

The failing tests don't pose an issue (verified it with manual testing). Would just like to document this here in the event that someone faces them as well.

Failed attempts at fixing:
- 'repair operation' for PPT at add & remove programs

**Comment by leeyh20** [comment] 2018-02-08 15:38
Is it related to https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered

**Comment by alexfjw** [comment] 2018-02-08 15:54
👍  Wow that's a good find. Yep, sounds like the problem right there.

**Comment by alexfjw** [comment] 2018-02-08 15:57
the office repair tip looks like a good one. I'll try that on #1465

**Comment by damithc** [comment] 2019-07-04 07:25
Closing as the issue is old

**Closed by damithc** 2019-07-04 07:25 UTC
Labels: f-PictureSlidesLab, f-SyncLab
